name: test
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - name: "Cache cargo"
        id: cache-cargo
        uses: "./.github/workflows/rust-cache.yml"
        with:
          runner: ubuntu-latest
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: extractions/setup-just@v2
      - run: just test
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - name: "Cache cargo"
        id: cache-cargo
        uses: "./.github/workflows/rust-cache.yml"
        with:
          runner: macos-latest
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: extractions/setup-just@v2
      - run: just test
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Cache cargo"
        id: cache-cargo
        uses: "./.github/workflows/rust-cache.yml"
        with:
          runner: windows-latest
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: extractions/setup-just@v2
      - run: just test
